version: '3'

services:
  postgres_transferencias:
    container_name: micro_db_transferencias
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=transferencias

  postgres_clientes:
    container_name: micro_db_clientes
    image: bitnami/postgresql
    ports:
      - 5433:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=clientes
  
  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_net

volumes:
  rabbitmq_data:

networks:
  rabbitmq_net:
    driver: bridge